# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_friend_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagepost',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
