# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_post_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagepost',
            field=models.FileField(default='null', upload_to='imageposts'),
        ),
    ]
